project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!slides_2021/"

website:
  title: "OSINT para Jornalistas"
  navbar:
    left:
      - text: Início
        href: index.qmd
      - text: Ferramentas
        href: ferramentas.qmd
      - text: Recursos
        href: recursos.qmd
      - text: Bibliografia
        href: bibliografia.qmd
      - text: Projetos
        href: projetos.qmd

format:
  html:
    theme: cosmo
    lang: pt-BR
