project:
  type: website
  output-dir: _site

website:
  title: "OSINT para Jornalistas"
  navbar:
    left:
      - text: Início
        href: index.qmd
      - text: Aulas
        menu:
          - text: "1. Fundamentos de OSINT"
            href: slides/aula_1.qmd
          - text: "2. Busca avançada na web"
            href: slides/aula_2.qmd
          - text: "3. Investigações visuais"
            href: slides/aula_3.qmd
      - text: Arquivamento
        href: arquivamento.qmd
      - text: Desafios
        href: desafios/index.qmd

format:
  html:
    theme: cosmo
    lang: pt-BR
